# Generated by Django 4.0.4 on 2022-04-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='land_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='pg_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='sale_house_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='sale_land_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='sale_pg_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='sale_shop_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='shop_id',
        ),
    ]
