# Generated by Django 4.0.4 on 2022-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_appointmentmodel_land_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='sale_house_id',
            field=models.IntegerField(null=True),
        ),
    ]
