# Generated by Django 4.0.4 on 2022-04-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_appointmentmodel_sale_house_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointmentModel',
        ),
    ]
