# Generated by Django 4.0.4 on 2022-04-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_appointmentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointmentModel',
        ),
    ]
