# Generated by Django 4.0.4 on 2022-04-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_delete_appointmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_appointmentModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
                ('sale_house_id', models.IntegerField()),
                ('land_id', models.IntegerField()),
                ('sale_land_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('sale_shop_id', models.IntegerField()),
                ('pg_id', models.IntegerField()),
                ('sale_pg_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('Mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_appointment_details',
            },
        ),
    ]
