# Generated by Django 4.0.4 on 2022-04-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_user_appointmentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_appointmentmodel',
            old_name='Mobile',
            new_name='mobile',
        ),
    ]
