# Generated by Django 4.0.4 on 2022-04-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_rename_mobile_user_appointmentmodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='land_id',
        ),
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='pg_id',
        ),
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='sale_house_id',
        ),
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='sale_land_id',
        ),
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='sale_pg_id',
        ),
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='sale_shop_id',
        ),
        migrations.RemoveField(
            model_name='user_appointmentmodel',
            name='shop_id',
        ),
    ]
