# Generated by Django 4.0.4 on 2022-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_user_appointmentmodel_land_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='land_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='pg_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='sale_house_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='sale_land_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='sale_pg_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='sale_shop_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_appointmentmodel',
            name='shop_id',
            field=models.IntegerField(null=True),
        ),
    ]
