# Generated by Django 4.0.4 on 2022-04-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_user_appointmentmodel_land_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='house_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'house_booking_details',
            },
        ),
        migrations.CreateModel(
            name='land_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'land_booking_details',
            },
        ),
        migrations.CreateModel(
            name='pg_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('pg_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pg_booking_details',
            },
        ),
        migrations.CreateModel(
            name='salehouse_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('salehouse_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salehouse_booking_details',
            },
        ),
        migrations.CreateModel(
            name='saleland_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('salehouse_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saleland_booking_details',
            },
        ),
        migrations.CreateModel(
            name='salepg_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('salepg_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salepg_booking_details',
            },
        ),
        migrations.CreateModel(
            name='saleshop_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('saleshop_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saleshop_booking_details',
            },
        ),
        migrations.CreateModel(
            name='shop_bookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('message', models.CharField(help_text='message', max_length=200)),
                ('booking_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop_booking_details',
            },
        ),
        migrations.DeleteModel(
            name='user_appointmentModel',
        ),
    ]
