# Generated by Django 4.0.4 on 2022-04-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_house_bookingmodel_land_bookingmodel_pg_bookingmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land_bookingmodel',
            old_name='house_id',
            new_name='land_id',
        ),
        migrations.RenameField(
            model_name='salehouse_bookingmodel',
            old_name='salehouse_id',
            new_name='sale_house_id',
        ),
        migrations.RenameField(
            model_name='saleland_bookingmodel',
            old_name='salehouse_id',
            new_name='sale_land_id',
        ),
        migrations.RenameField(
            model_name='salepg_bookingmodel',
            old_name='salepg_id',
            new_name='sale_pg_id',
        ),
        migrations.RenameField(
            model_name='saleshop_bookingmodel',
            old_name='saleshop_id',
            new_name='sale_shop_id',
        ),
    ]
