# Generated by Django 4.0.4 on 2022-04-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_rename_house_id_land_bookingmodel_land_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_bookingmodel',
            old_name='booking_id',
            new_name='house_booking_id',
        ),
        migrations.RenameField(
            model_name='land_bookingmodel',
            old_name='booking_id',
            new_name='land_booking_id',
        ),
        migrations.RenameField(
            model_name='pg_bookingmodel',
            old_name='booking_id',
            new_name='pg_booking_id',
        ),
        migrations.RenameField(
            model_name='salehouse_bookingmodel',
            old_name='booking_id',
            new_name='salehouse_booking_id',
        ),
        migrations.RenameField(
            model_name='saleland_bookingmodel',
            old_name='booking_id',
            new_name='saleland_booking_id',
        ),
        migrations.RenameField(
            model_name='salepg_bookingmodel',
            old_name='booking_id',
            new_name='salepg_booking_id',
        ),
        migrations.RenameField(
            model_name='saleshop_bookingmodel',
            old_name='booking_id',
            new_name='saleshop_booking_id',
        ),
        migrations.RenameField(
            model_name='shop_bookingmodel',
            old_name='booking_id',
            new_name='shop_booking_id',
        ),
    ]
